background #0e141c
foreground #dde3ee
cursor #cfe1ff

color0  #0e141c
color1  #ffd7d2
color2  #dfddff
color3  #d7dfff
color4  #cfe1ff
color5  #3b9eff
color6  #9696cb
color7  #dde3ee
color8  #b9bfca
color9  #ffd7d2
color10 #dfddff
color11 #d7dfff
color12 #cfe1ff
color13 #3b9eff
color14 #9696cb
color15 #dde3ee
