[config]

[templates.mango_focuscolor]
input_path = '~/.config/matugen/templates/mango-focuscolor.conf'
output_path = '~/.config/color-engine/mango-focuscolor.conf'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/theme.conf'
post_hook = 'pkill -SIGUSR1 kitty || true'

[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty.template'
output_path = '~/.config/ghostty/themes/tema_matugen'
post_hook = 'pkill -SIGUSR2 ghostty || true'

[templates.alacritty]
input_path = "~/.config/matugen/templates/alacritty.template"
output_path = "~/.config/alacritty/colors.toml"

#-------Colores_rofi-------
[templates.rofi_launcher_colors_wallpaper]
input_path = '~/.config/matugen/templates/rofi-launcher-colors-wallpaper.rasi'
output_path = '~/.config/rofi/colors/matugen-wallpaper.rasi'




















